### ISSUE TITLE
Feed Not Working

### ISSUE THREAD

**Issue by bkubic** [Elaniobro/MMM-nyc-transit#2] opened 2019-08-14 01:50 UTC
I've installed the module as per instructions and received an MTA API key. However, the only thing that appears on the MM is the header "Next Train" - no train feed shows up. Any help? 

```
{
    module: 'MMM-nyc-transit'
    position: 'top_bar',
    header: 'Next Train',
    config: {
        apiKey: 'my_api_key',
        stations: [158],
        updateInterval: 60000
    }
}
```

**Comment by Elaniobro** [comment] 2019-08-14 13:24
@bkubic I have experienced the same thing in the past. I am not sure if its the code, the mirror and or a delay in getting the information.

Can you please provide me more information about your setup?

- what type of pi do you have
- what size sd card
- how many other modules
- does the mirror start up
- does the module work with another train station id, or perhaps two ids?

Thanks!

**Comment by bkubic** [comment] 2019-08-14 16:02
-     what type of pi do you have? **Pi 3 B+**
-     what size sd card? **16gb**
-     how many other modules? **4**
-     does the mirror start up? **yes**
-     does the module work with another train station id, or perhaps two ids? **no station ids that i've tried have worked, including multiples**
-     what browser are you using? **Electron (whatever the base install of MM is)**

**Comment by Elaniobro** [comment] 2019-08-14 16:25
@bkubic would you please post your entire config (sanitize it for api keys). 

Do other modules work? Does he mirror work at all?

**Comment by bkubic** [comment] 2019-08-14 16:27
Not at home so I don't have access to the full config right now, but every
other module works as expected, and the mirror works fine. It's just this
module that shows the "Next Train" header and nothing underneath.

**Comment by Elaniobro** [comment] 2019-08-14 18:08
@bkubic copy that. I think I see the issue. Might take me a few days to get around to resolving it. I'll fix it asap! Thanks for reporting this :)

**Comment by Elaniobro** [comment] 2019-08-15 03:15
@bkubic here is what I am seeing with station id 158:
![Screen Shot 2019-08-14 at 23 14 41](https://user-images.githubusercontent.com/710847/63070491-656fe480-bee9-11e9-95c6-3ff8c75eef5b.png)

**Comment by bkubic** [comment] 2019-08-15 12:15
Still nothing. Here's what I see: 
![2019-08-15-081417_1920x1080_scrot](https://user-images.githubusercontent.com/10870058/63093898-d4bef600-bf34-11e9-887a-5284bf216e3f.png)

**Comment by bkubic** [comment] 2019-08-15 12:16
Full config.js for reference:

````
ar config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff", "192.168.1.1/24"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: 'MMM-Remote-Control'
		},
		{
			module: "clock",
			position: "top_left",
			config: {
				displaySeconds: false,
				timezone: 'America/New_York'
			}
		},
		{
			module: 'MMM-nyc-transit',
			position: "top_bar",
			header: "Next Train",
			config: {
				apiKey: 'APIKEY',
				stations: [158],
				updateInterval: 60000
			}
		},
		{
			module: 'MMM-MTA-NextBus',
			position: "top_left",
			config: {
				apiKey: 'APIKEY',
				busStopCode: '401897'
			}
		},
		{
			module: "MMM-darksky-hourly",
			position: "top_right",
			config: {
				apiKey: 'APIKEY',
				latitude: 40.788440,
				longitude: -73.974035,
				twentyFourHourTime: false
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
````

**Comment by Elaniobro** [comment] 2019-08-20 03:18
@bkubic; curious does the module work if you reboot the mirror? I have seen it work with your stationID of `158` and also seen it fail. Trying to trace it down to the root cause. Thank you for your patience :)

**Comment by Elaniobro** [comment] 2019-08-20 03:21
Also, I noticed your config is missing the `walkingTime: 0` key value pair. While I do add a default, would you please try adding that in as well to test? Thanks!

**Comment by bkubic** [comment] 2019-08-20 17:17
Rebooting didn't have an effect. I originally had walkingTime in there, but
when it didn't work I tried removing to see if that was issue, and it still
didn't work.

**Comment by zstein22** [comment] 2019-08-23 14:36
same issue here. trying to get station 607 to work, but nothing is coming up. Ive reset tons of time and left it open for a while as well.

**Comment by Elaniobro** [comment] 2019-08-23 16:01
@zstein22 & @bkubic could you try re-starting it and using the following: `stations: [237,238]` for a sanity check :) 

I am still digging into this, but will be out of pocket for a few days, PR's are also welcome :) 

Stay tuned and thanks for your patience!

**Comment by mraimi** [comment] 2019-08-25 20:23
I'm in a similar situation. The default station ids work (`237` and `238`) but other stations such as `273` and `461` don't work.

**Comment by Elaniobro** [comment] 2019-08-26 00:39
@mraimi, @bkubic  & @zstein22 would you all please mind posting your `package.json` files, so I may see and try to replicate the same environment to debug? Thanks!

**Comment by Kendiggity973** [comment] 2019-09-06 00:01
Hey Elaniobro. My train stops arent working either. I can post my package.json files.

**Comment by Kendiggity973** [comment] 2019-09-06 00:03
{
  "name": "MMM-nyc-transit",
  "version": "1.0.0",
  "description": "New York City realtime transit module for magic mirror",
  "main": "MMM-nyc-transit.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "lint": "eslint **/*.js --ignore-pattern node_modules/"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Elaniobro/MMM-nyc-transit"
  },
  "keywords": [
    "Magic",
    "Mirror",
    "Magic Mirror",
    "MMM",
    "NYC",
    "transit",
    "subway",
    "bus"
  ],
  "author": {
    "name": "Elan Trybuch",
    "email": "elan@trybuch.com",
    "url": "https://elan.trybuch.com"
  },
  "license": "MIT",
  "devDependencies": {
    "chalk": "^2.4.1",
    "eslint": "^6.0.1",
    "fs-extra": "^7.0.0",
    "husky": "^3.0.0",
    "mta-realtime-subway-departures": "0.0.13"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run lint"
    }
  }
}

**Comment by Kendiggity973** [comment] 2019-09-06 00:04
i was also wondering if there was a way to make it not a ticker and more of a list?

**Comment by Elaniobro** [comment] 2019-09-07 18:54
@Kendiggity973 thanks for commenting and posting here. Which station ID are you using?

I will begin looking into this issue again this week. As for List/Ticker, feel free to create a separate issue to track that. Not sure when I will get to it, but I hope sooner than later!

**Comment by Kendiggity973** [comment] 2019-09-08 21:55
@Elaniobro Im using various Trains. probably alist of a good 10 or so. however, ive done testing and it seems no trains aside from the default ones pull data at all

**Comment by Elaniobro** [comment] 2019-09-09 03:31
@Kendiggity973, @mraimi, @bkubic & @zstein22, wanting to rule out the obvious: have you all received your MTA api key and placed it int he `config.js` file for the modules?

**Comment by Kendiggity973** [comment] 2019-09-09 04:19
yes.

**Comment by dahlio** [comment] 2019-09-10 03:11
Hi there...can provide files if needed too...using stations 96 and 114. It is only populating for 96, not 114.

Thanks for this - such a great module!

**Comment by Kendiggity973** [comment] 2019-09-11 00:39
@Elaniobro. NYC MTA offered like 6 different feeds. are you sure that it isnt because you have access to all of them and we only have the standards?

**Comment by Elaniobro** [comment] 2019-09-11 15:11
@Kendiggity973 Yea, I am sure it is the right feed. It is using the Real Time Data Transfer Feed format. I believe the issue may be in the response it self; if a train is not scheduled, there is an empty response which results in an error in the `forEach()` loop (nothing to loop over). I do have an update to safeguard against that error. Let me verify the code and make that update later today. 

Also, I am running this locally via electron App to debug and am not running this on a Raspberry Pi. Lastly, I developed this for and on a Raspberry Pi0w

If the minor update does not resolve your issues, will you please share with me the `package.json` & `config.js` file for your magic mirror itself? This way I can make sure I am seeing what you see.

**Comment by Kendiggity973** [comment] 2019-09-11 15:54
Sure I can do that once I get home

**Comment by Kendiggity973** [comment] 2019-09-12 00:47
@Elaniobro Still no good on my stops.

**Comment by Elaniobro** [comment] 2019-09-12 01:42
@Kendiggity973 please post your `package.json` for the magicmirror as well as the `config.js` 

Thanks!

**Comment by Kendiggity973** [comment] 2019-09-12 01:47
Im currently reinstalling MM and the plugin with debian buster to see if
its still an issue.
if it is i will post it


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Kendiggity973** [comment] 2019-09-12 02:01
Give it a shot, Im getting nothing still

[Files.zip](https://github.com/Elaniobro/MMM-nyc-transit/files/3603336/Files.zip)

**Comment by Elaniobro** [comment] 2019-09-12 02:33
@Kendiggity973 Thanks for the files(s) I deleted the link to keep your privacy.

I believe I see the issue now, `name` is undefined for the station. I will need to dig into this.

**Comment by Elaniobro** [comment] 2019-09-12 05:52
This should be resolved now. Please let me know and I will close this issue.

**Closed** 2019-09-13 13:02 UTC
Labels: 🐛 bug
