### ISSUE TITLE
Needs list version

### ISSUE THREAD

**Issue by Kendiggity973** [Elaniobro/MMM-nyc-transit#8] opened 2019-09-12 20:26 UTC
I’m thinking a list version would make this better. Such as

L Train Halsey stop: Arrives in 5 minutes
M train: Arrives in 12 minutes

With a countdown possibly color coded for time remaining based on walk time.

My mirror will be pulling a lot of stations data and I feel like a ticker would be inconvenient as a form of display

**Comment by Elaniobro** [comment] 2019-09-16 22:22
This issue is now a duplicate of #9 and will be tracked there.

**Closed by Elaniobro** 2019-09-16 22:22 UTC
Labels: :white_large_square: major, 💡 enhancement
